### ISSUE TITLE
implementation of your keyboard for Librem 5 upstream

### ISSUE THREAD

**Issue by okias** [vitSkalicky/klavesnice#3]
Hello Vít,
must say I like your Android keyboard pretty much. I know it's pretty serious work behind this keyboard and I wonder if you woud be willing do same layout for Librem 5 phone [1]. I know my request is out-of-scope of your original project, but I think your work could be even accepted by upstream in this new Linux based phone and could be opportunity to form great user experience for Czech users.
Here is screenshot of actual keyboard progress on Librem 5 [2].

Thank you for your time! 

[1] https://source.puri.sm/Librem5/squeekboard/
[2] https://puri.sm/posts/librem-5-july-update/

**Comment by vitSkalicky** [comment]
Sorry to react so late - I do not maintain this project much anymore. I have no experience with mobile linux and I have tons of other work to do right now.

In Czech you need to type these accented characters: á,é,í,ý,ó,ú,ř,š,č,ž,ď,ť,ň,ě,ů. On Android, users usually type them by holding the unaccented character and then selecting accented from floating selector. I prefer using 'dead keys', which means that there is a key for the accent and when you press it the next character is accented. That is how this app works. The ů is still typed using the floating selector.
