### ISSUE TITLE
Emoji keyboard typing Korean (?) symbols instead of emojis.

### ISSUE THREAD

**Issue by michallan23** [vitSkalicky/klavesnice#6]
Hello, I love the keyboard but I've had this issue since the beginning. For example, instead of the emoji 🙂 the emoji keyboard would put this symbol: 
Any chance you can look into it? Thanks!

**Comment by vitSkalicky** [comment]
That is an interesting bug, but I unfortunately won't fix it any time soon because I don't have much time now. I would appreciate if someone made a pull request with fix, but I'm not planning on fixing it myself.
