### ISSUE TITLE
Klávesnice vkládá diakritiku obráceně

### ISSUE THREAD

**Issue by MichalNemec** [vitSkalicky/klavesnice#7]
Pokud napíšu například i a pak máčknu diakritiku -> í tak se tak nestane
Pokud máčknu diakritiku a pak i -> í

Bylo by možné toto nastavit v nastavení? + dark theme

**Comment by vitSkalicky** [comment]
Obrátit psaní diakritiky by bylo z technických důvodů poměrně komplikované. Tmavý motiv klávesnice umí, jen se musí ručně zapnout v nastavení > Vzhled a rozvrhžení > Motiv.
